"""Initial schema

Revision ID: 3ffad56200ff
Revises: 
Create Date: 2026-05-08 02:52:44.978941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ffad56200ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('users')]
    
    if 'verify_otp_hash' not in columns:
        op.add_column('users', sa.Column('verify_otp_hash', sa.String(length=64), nullable=True))
    if 'verify_otp_expires_at' not in columns:
        op.add_column('users', sa.Column('verify_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    if 'reset_otp_hash' not in columns:
        op.add_column('users', sa.Column('reset_otp_hash', sa.String(length=64), nullable=True))
    if 'reset_otp_expires_at' not in columns:
        op.add_column('users', sa.Column('reset_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_otp_expires_at')
    op.drop_column('users', 'reset_otp_hash')
    op.drop_column('users', 'verify_otp_expires_at')
    op.drop_column('users', 'verify_otp_hash')
    # ### end Alembic commands ###
